print("===========================================================")
print("==============           DATA PRIBADI          ============")
print("===========================================================")
print("NAMA               : ZALDI ZOFYAN")
print("Tempat , Tgl Lahir : Lingkung Bore,29 Desember 2005")
print("Agama              : Kristen")
print("Alamat             : lingkung,Desa Berinding, Kec.kopang")
print("Handphone          : 081959663170")
print("Status             : Belum Menikah")
print("E_Mail             : zaldijumus@gmail.com")
print()
print("===========================================================")
print("                      DATA PENDIDIKAN                      ")
print("===========================================================")
print("MI                 : MI NW LINGKUNG (2011-2017)")
print("SMP                : SMPN 6 KOPANG  (2017-2020)")
print("SMK                : SMKN 1 KOPANG  (2020-2023)")
print("===========================================================")